# =================== DINASTIAPI STACK PARA PORTAINER ===================
# Stack completa do DinastiAPI com todos os serviços necessários
# Configurada para uso em produção com Docker Swarm via Portainer

services:
  dinastiapi_private:
    image: dinastiapi/dinastiapi-private:latest # CONSULTE AS VERSÕES DISPONÍVEIS NO DOCKER HUB https://hub.docker.com/r/dinastiapi/dinastiapi-private
    networks:
      - network_public
    environment:
      # =================== ADMIN & AUTHENTICATION ===================
      - DINASTIAPI_ADMIN_TOKEN=SEU_TOKEN_AQUI_DO_ADMIN  # SEU TOKEN AQUI DO ADMIN
      - DINASTIAPI_ADDRESS=suaapi.seudominio.com  # SEU DOMINIO AQUI DA API
      - DINASTIAPI_PORT=8080

      - SERVER_IP=  # SEU IP AQUI DA API (EX: 127.0.0.1, 192.168.1.100, etc.)
      - LICENSE_KEY=  # SEU LICENSE KEY AQUI LIBERADO PELO DINASTIAPI
      - INSTANCE_ID=  # SEU IDENTIFICADOR AQUI DO SERVIDOR (EX: SERVIDOR_1, SERVIDOR_2, etc.)

      - LOG_TYPE=console  # TIPO DE LOG (console, json)
      - LOG_COLOR=true  # COR DO LOG (true, false)
      
      # =================== DATABASE CONFIGURATION ===================
      # Option 1: Individual database variables (current method)
      - DB_USER=dinastiapi
      - DB_PASSWORD=SENHA_AQUI_DO_BANCO_DE_DADOS
      - DB_NAME=dinastiapi
      - DB_HOST=postgres_dinastiapi
      - DB_PORT=5432
      - DB_SSLMODE=disable
      - DB_SCHEMA=public

      # Option 2: Single database connection string (production method)
      # Uncomment the line below and comment out the individual variables above
      # - DATABASE_URL=postgres://dinastiapi:SENHA_AQUI_DO_BANCO_DE_DADOS@postgres_dinastiapi:5432/postgres_dinastiapi?sslmode=disable&search_path=public
      # For managed databases: DATABASE_URL=postgres://user:pass@managed-db.example.com:5432/dinastiapi?sslmode=require

      # =================== SESSION & TIMEZONE ===================
      - TZ=America/Sao_Paulo
      - SESSION_DEVICE_NAME=DinastiAPI

      # =================== WEBHOOK INDIVIDUAL POR INSTANICA CONFIGURATIONS ===================
      # "json" or "form" for the default
      - WEBHOOK_FORMAT=json

      # Timeout principal da requisição HTTP
      - WEBHOOK_TIMEOUT=30s

      # Número máximo de tentativas de retry
      - WEBHOOK_MAX_RETRIES=3

      # Delay inicial entre tentativas
      - WEBHOOK_RETRY_DELAY=2s

      # Delay máximo entre tentativas (cap do backoff exponencial)
      - WEBHOOK_MAX_RETRY_DELAY=30s

      # Fator de multiplicação para backoff exponencial
      - WEBHOOK_BACKOFF_FACTOR=2.0

      # Número máximo de requisições simultâneas
      - WEBHOOK_MAX_CONCURRENCY=100

      # =================== GLOBAL SKIP MEDIA DOWNLOAD ===================
      # Enable/disable global skip media download for all users
      - GLOBAL_SKIP_MEDIA_DOWNLOAD=false # ESCOLHA SE VAI ATIVAR O SKIP MEDIA DOWNLOAD GLOBAL
      # Skip events from WhatsApp groups
      - GLOBAL_SKIP_GROUPS=false # ESCOLHA SE VAI ATIVAR O SKIP GROUPS GLOBAL
      # Skip events from WhatsApp newsletters
      - GLOBAL_SKIP_NEWSLETTERS=false # ESCOLHA SE VAI ATIVAR O SKIP NEWSLETTERS GLOBAL
      # Skip events from WhatsApp broadcasts and status updates
      - GLOBAL_SKIP_BROADCASTS=false # ESCOLHA SE VAI ATIVAR O SKIP BROADCASTS GLOBAL
      # Skip user's own messages (sent messages)
      - GLOBAL_SKIP_OWN_MESSAGES=false # ESCOLHA SE VAI ATIVAR O SKIP OWN MESSAGES GLOBAL
      # Skip call events (offers, accepts, terminates)
      - GLOBAL_SKIP_CALLS=false # ESCOLHA SE VAI ATIVAR O SKIP CALLS GLOBAL

      # =================== GLOBAL S3 CONFIGURATION ===================
      # Enable/disable global S3 for media processing
      - GLOBAL_S3_ENABLED=false # ESCOLHA SE VAI ATIVAR O S3 GLOBAL
      # S3 endpoint (leave empty for AWS S3)
      - GLOBAL_S3_ENDPOINT=
      # S3 region
      - GLOBAL_S3_REGION=us-east-1
      # S3 bucket name for global media
      - GLOBAL_S3_BUCKET=
      # S3 access key
      - GLOBAL_S3_ACCESS_KEY=
      # S3 secret key
      - GLOBAL_S3_SECRET_KEY=
      # Use path-style URLs (true for MinIO/compatible)
      - GLOBAL_S3_PATH_STYLE=true
      # Custom public URL for S3 objects (optional)
      - GLOBAL_S3_PUBLIC_URL=
      # Media delivery method: base64, url, or both
      - GLOBAL_S3_MEDIA_DELIVERY=base64
      # Retention days for media (0 = no expiration)
      - GLOBAL_S3_RETENTION_DAYS=0

      # =================== GLOBAL WEBHOOK CONFIGURATION ===================
      # Enable/disable global webhook for all users
      - GLOBAL_WEBHOOK_ENABLED=false # ESCOLHA SE VAI ATIVAR O WEBHOOK GLOBAL
      # URL endpoint to receive all global events
      - GLOBAL_WEBHOOK_URL=https://hook.dinastiapi.com/webhook/global-events # SEU WEBHOOK AQUI
      # Event types to capture (comma-separated or "All")
      - GLOBAL_WEBHOOK_EVENTS=All 
      # HTTP request timeout for webhook calls
      - GLOBAL_WEBHOOK_TIMEOUT=30s
      # Number of retry attempts for failed webhook calls
      - GLOBAL_WEBHOOK_RETRY_COUNT=3
      # Initial delay between retries
      - GLOBAL_WEBHOOK_RETRY_DELAY=2s
      # Maximum delay between retries (exponential backoff cap)
      - GLOBAL_WEBHOOK_MAX_RETRY_DELAY=30s
      # Exponential backoff multiplier for retry delays
      - GLOBAL_WEBHOOK_BACKOFF_FACTOR=2.0
      # Maximum concurrent webhook requests (production ready)
      - GLOBAL_WEBHOOK_CONCURRENCY=100

      # =================== GLOBAL RABBITMQ BASIC CONFIGURATION ===================
      # Enable/disable global RabbitMQ for all users
      - GLOBAL_RABBITMQ_ENABLED=false # ESCOLHA SE VAI ATIVAR O RABBITMQ GLOBAL
      # RabbitMQ connection URL (production cluster)
      - GLOBAL_RABBITMQ_URL=amqp://dinastiapi:SENHA_AQUI_DO_RABBITMQ@rabbitmq_dinastiapi:5672/dinastiapi
      # Event types to publish (comma-separated or "All")
      - GLOBAL_RABBITMQ_EVENTS=All
      # Exchange name for global events
      - GLOBAL_RABBITMQ_EXCHANGE=dinastiapi.global.prod
      - GLOBAL_RABBITMQ_EXCHANGE_TYPE=topic
      # Queue name for global events
      # ===== OPÇÃO 1: FILA ÚNICA (ATUAL) =====
      # GLOBAL_RABBITMQ_QUEUE=dinastiapi.events
      # GLOBAL_RABBITMQ_ROUTING_KEY=events.#
      # ===== OPÇÃO 2: FILAS POR EVENTO (NOVO) =====
      - GLOBAL_RABBITMQ_QUEUE=dinastiapi_{event_type}_events
      - GLOBAL_RABBITMQ_ROUTING_KEY=events.{event_type}.#
      # - GLOBAL_RABBITMQ_QUEUE=dinastiapi.events.prod
      - GLOBAL_RABBITMQ_QUEUE_TYPE=classic
      # Routing key pattern for message routing
      - GLOBAL_RABBITMQ_ROUTING_KEY=events.#
      # Make exchange and queue durable (survive broker restart)
      - GLOBAL_RABBITMQ_DURABLE=true
      # Auto-delete exchange/queue when not in use
      - GLOBAL_RABBITMQ_AUTO_DELETE=false
      # Message delivery mode (2=persistent for production)
      - GLOBAL_RABBITMQ_DELIVERY_MODE=2
      # Exclusive queue for production stability
      - GLOBAL_RABBITMQ_EXCLUSIVE=false
      # No wait for queue creation
      - GLOBAL_RABBITMQ_NO_WAIT=false

      # =================== GLOBAL RABBITMQ PERFORMANCE TUNING (PRODUCTION) ===================
      # High-performance connection pool for production load
      - GLOBAL_RABBITMQ_CONNECTION_POOL_SIZE=50
      # High worker count for concurrent message processing
      - GLOBAL_RABBITMQ_WORKER_COUNT=100
      # Large buffer for high-volume message handling
      - GLOBAL_RABBITMQ_QUEUE_BUFFER_SIZE=100000
      # Enable message batching for maximum throughput
      - GLOBAL_RABBITMQ_ENABLE_BATCHING=true
      # Large batch size for production efficiency
      - GLOBAL_RABBITMQ_BATCH_SIZE=1000
      # Fast batch timeout for low latency
      - GLOBAL_RABBITMQ_BATCH_TIMEOUT_MS=100

      # =================== GLOBAL RABBITMQ RELIABILITY & RESILIENCE ===================
      # Circuit breaker: failures before opening circuit (production settings)
      - GLOBAL_RABBITMQ_CIRCUIT_BREAKER_THRESHOLD=20
      # Circuit breaker: longer timeout for production stability
      - GLOBAL_RABBITMQ_CIRCUIT_BREAKER_TIMEOUT_S=60
      # Extended timeout for individual publish operations
      - GLOBAL_RABBITMQ_PUBLISH_TIMEOUT_MS=10000
      # More retry attempts for production reliability
      - GLOBAL_RABBITMQ_MAX_RETRIES=5
      # Shorter delay between retries for faster recovery
      - GLOBAL_RABBITMQ_RETRY_DELAY_MS=500

      # =================== GLOBAL RABBITMQ MONITORING & LOGGING ===================
      # Frequent metrics collection for production monitoring
      - GLOBAL_RABBITMQ_METRICS_INTERVAL_S=5
      # Enable detailed logging for production troubleshooting
      - GLOBAL_RABBITMQ_ENABLE_DETAILED_LOGS=true
      # Enable metrics logging for production monitoring
      - GLOBAL_RABBITMQ_ENABLE_METRICS_LOG=true

      # =================== GLOBAL RABBITMQ QOS & MESSAGE SETTINGS ===================
      # High QoS prefetch for optimal message distribution
      - GLOBAL_RABBITMQ_QOS_PREFETCH_COUNT=200
      # Mandatory delivery for production reliability
      - GLOBAL_RABBITMQ_MANDATORY=false
      # No immediate flag for production stability
      - GLOBAL_RABBITMQ_IMMEDIATE=false

      # =================== GLOBAL RABBITMQ ADVANCED FEATURES (PRODUCTION) ===================
      # Enable compression for bandwidth optimization in production
      - GLOBAL_RABBITMQ_ENABLE_COMPRESSION=true
      # Enable persistence for production data durability
      - GLOBAL_RABBITMQ_ENABLE_PERSISTENCE=true
      # Enable confirmations for production reliability
      - GLOBAL_RABBITMQ_ENABLE_CONFIRMATION=true

    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints: [node.role == manager]
      resources:
        limits:
          cpus: "2"      # Increased for RabbitMQ Global performance
          memory: 2GB    # Increased for high-throughput message processing
        reservations:
          cpus: "1"
          memory: 1GB
      labels:
        - traefik.enable=true
        - traefik.http.routers.dinastiapi_private.rule=Host(`api.dinastiapi.app`)
        - traefik.http.routers.dinastiapi_private.entrypoints=websecure
        - traefik.http.routers.dinastiapi_private.priority=1
        - traefik.http.routers.dinastiapi_private.tls.certresolver=letsencryptresolver
        - traefik.http.routers.dinastiapi_private.service=dinastiapi_private
        - traefik.http.services.dinastiapi_private.loadbalancer.server.port=8080
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s

  # =================== BANCO DE DADOS POSTGRESQL ===================
  postgres_dinastiapi:
    image: postgres:16-alpine
    environment:
      - POSTGRES_USER=dinastiapi # USUÁRIO DO BANCO DE DADOS
      - POSTGRES_PASSWORD=SENHA_AQUI_DO_BANCO_DE_DADOS # SENHA DO BANCO DE DADOS
      - POSTGRES_DB=dinastiapi # NOME DO BANCO DE DADOS
    volumes:
      - postgres_data_dinastiapi:/var/lib/postgresql/data
    networks: 
      - network_public
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
      resources:
        limits:
          cpus: '0.5' # CPU DO POSTGRES
          memory: 512MB # MEMÓRIA DO POSTGRES
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-dinastiapi} -d ${POSTGRES_DB:-dinastiapi}"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  # =================== RABBITMQ (MENSAGERIA) ===================
  rabbitmq_dinastiapi:
    image: rabbitmq:4-management-alpine
    environment:
      - RABBITMQ_DEFAULT_USER=dinastiapi # USUÁRIO DO RABBITMQ
      - RABBITMQ_DEFAULT_PASS=SENHA_AQUI_DO_RABBITMQ # SENHA DO RABBITMQ
      - RABBITMQ_DEFAULT_VHOST=dinastiapi # VHOST DO RABBITMQ
    volumes:
      - rabbitmq_data_dinastiapi:/var/lib/rabbitmq
    networks:
      - network_public
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
      resources:
        limits:
          cpus: '0.5' # CPU DO RABBITMQ
          memory: 512MB # MEMÓRIA DO RABBITMQ
      labels:
        - traefik.enable=true
        - traefik.http.routers.rabbitmq_dinastiapi.rule=Host(`rabbitmq.dinastiapi.app`) # SEU DOMINIO AQUI DO RABBITMQ
        - traefik.http.routers.rabbitmq_dinastiapi.entrypoints=websecure
        - traefik.http.routers.rabbitmq_dinastiapi.tls.certresolver=letsencryptresolver
        - traefik.http.routers.rabbitmq_dinastiapi.service=rabbitmq_dinastiapi
        - traefik.http.services.rabbitmq_dinastiapi.loadbalancer.server.port=15672
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

volumes:
  postgres_data_dinastiapi:
    name: postgres_data_dinastiapi
    external: true
  rabbitmq_data_dinastiapi:
    name: rabbitmq_data_dinastiapi
    external: true

networks:
  network_public:
    name: network_public
    external: true